name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec

    - name: Run rubocop
      run: bundle exec rubocop

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t geoip-service .

    - name: Remove existing container
      run: docker rm -f geoip-container || true

    - name: Run Docker container
      run: docker run -d -p 4567:4567 --name geoip-container geoip-service

    - name: Wait for container to start
      run: sleep 10

    - name: Test Docker container
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" 'http://localhost:4567/geoip?ip=8.8.8.8')
        if [ $response -eq 200 ]; then
          echo "Docker container is running and responding correctly"
        else
          echo "Docker container test failed"
          exit 1
        fi

    - name: Stop Docker container
      run: docker stop geoip-container